import type { Metadata } from 'next'
import { SessionProvider } from "next-auth/react"
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import './globals.css'
 
export const metadata: Metadata = {
  title: 'Faltas',
  description: 'Generated by create next app',
}
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html>
        <body>          
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}